# Database configuration
jdbc.url=jdbc:mysql://localhost:3306/spring?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.username=root
jdbc.password=Amecho00#

# MyBatis configuration
mybatis.mapper-locations=classpath*:mapper/*.xml
